name: serial_csv
description: High performance CSV encoder and decoder with retained types and nullability.
version: 0.1.0
repository: https://github.com/Tienisto/serial_csv
topics:
  - csv
  - serialization
  - deserialization
  - encode
  - decode

environment:
  sdk: '>=2.19.6 <4.0.0'

dev_dependencies:
  csv: ^5.0.2
  lints: ^2.0.0
  test: ^1.21.0