name: serial_csv
description: High performance CSV encoder and decoder with retained types and nullability.
version: 0.2.1
repository: https://github.com/Tienisto/serial_csv
topics:
  - csv
  - serialization
  - deserialization
  - encode
  - decode

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  csv: 5.0.2
  csvwriter: 1.3.0
  fast_csv: 0.1.44
  lints: 2.0.1
  test: 1.24.3
